name: Fetch SBIRS-GEO-6 data
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data 
        uses: githubocto/flat@v3
        with:
          http_url: https://celestrak.com/NORAD/elements/active.txt
          downloaded_filename: active.txt

