name: Fetch SBIRS-GEO-6 data
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data 
        uses: githubocto/flat@v3
        with:
          http_url: http://celestrak.org/NORAD/elements/gp.php?INTDES=2022-092&FORMAT=TLE
          downloaded_filename: 2022-092.txt

